In [1]:
# Vorlesungen über mathematische Physik
# Gustav Kirchhoff, 1883

# Book digitized by Google from the library of Oxford University
# and uploaded to the Internet Archive by user tpb.

# https://archive.org/details/vorlesungenberm00kircgoog
# https://archive.org/details/vorlesungenberm01kircgoog

In [2]:
import os
import pandas as pd

In [3]:
last = 465

df = pd.DataFrame(index=range(1, last + 1))

df.loc[  1, 'lect'] =  1
df.loc[ 13, 'lect'] =  2
df.loc[ 24, 'lect'] =  3
df.loc[ 33, 'lect'] =  4
df.loc[ 40, 'lect'] =  5

df.loc[ 53, 'lect'] =  6
df.loc[ 62, 'lect'] =  7
df.loc[ 77, 'lect'] =  8
df.loc[ 86, 'lect'] =  9
df.loc[ 95, 'lect'] = 10

df.loc[109, 'lect'] = 11
df.loc[125, 'lect'] = 12
df.loc[135, 'lect'] = 13
df.loc[150, 'lect'] = 14
df.loc[161, 'lect'] = 15

df.loc[173, 'lect'] = 16
df.loc[197, 'lect'] = 17
df.loc[214, 'lect'] = 18
df.loc[233, 'lect'] = 19
df.loc[251, 'lect'] = 20

df.loc[273, 'lect'] = 21
df.loc[290, 'lect'] = 22
df.loc[308, 'lect'] = 23
df.loc[322, 'lect'] = 24
df.loc[347, 'lect'] = 25


df.loc[369, 'lect'] = 26
df.loc[388, 'lect'] = 27
df.loc[406, 'lect'] = 28
df.loc[428, 'lect'] = 29
df.loc[449, 'lect'] = 30

df = df.ffill().astype(int)

assert df['lect'].is_monotonic_increasing

df

     lect
1       1
2       1
3       1
4       1
5       1
..    ...
461    30
462    30
463    30
464    30
465    30

[465 rows x 1 columns]

In [4]:
# We have two tif directories.
# I am sure why. Their history is a mystery.
# Both are good but not perfect.

dir00 = 'vorlesungenberm00kircgoog_tif'
dir01 = 'vorlesungenberm01kircgoog_tif'

files00 = sorted(os.listdir(dir00))
files01 = sorted(os.listdir(dir01))

In [5]:
# Slice to get just the lectures.
# Remove duplicate / error scans.

## There are extra pages.
## If there are a bad scans and they realize it,
## they rescan but the bad scans remains?

files00 = files00[16:489]
files01 = files01[16:487]

files00.remove('vorlesungenberm00kircgoog_0284.tif')
files00.remove('vorlesungenberm00kircgoog_0285.tif')
files00.remove('vorlesungenberm00kircgoog_0286.tif')
files00.remove('vorlesungenberm00kircgoog_0287.tif')
files00.remove('vorlesungenberm00kircgoog_0288.tif')
files00.remove('vorlesungenberm00kircgoog_0289.tif')
files00.remove('vorlesungenberm00kircgoog_0460.tif')
files00.remove('vorlesungenberm00kircgoog_0461.tif')

files01.remove('vorlesungenberm01kircgoog_0212.tif')
files01.remove('vorlesungenberm01kircgoog_0213.tif')
files01.remove('vorlesungenberm01kircgoog_0254.tif')
files01.remove('vorlesungenberm01kircgoog_0255.tif')
files01.remove('vorlesungenberm01kircgoog_0458.tif')
files01.remove('vorlesungenberm01kircgoog_0459.tif')

assert len(files00) == last
assert len(files01) == last

In [6]:
df['path00'] = [os.path.join(dir00, file) for file in files00]
df['path01'] = [os.path.join(dir01, file) for file in files01]

assert df['path00'].is_unique
assert df['path01'].is_unique

assert all([path.count('vorlesungenberm00') == 2 for path in df['path00']])
assert all([path.count('vorlesungenberm01') == 2 for path in df['path01']])

df.to_csv('table_10.csv')

df

,lect,path00,path01
1,1,vorlesungenberm00kircgoog_tif/vorlesungenberm0...,vorlesungenberm01kircgoog_tif/vorlesungenberm0...
2,1,vorlesungenberm00kircgoog_tif/vorlesungenberm0...,vorlesungenberm01kircgoog_tif/vorlesungenberm0...
3,1,vorlesungenberm00kircgoog_tif/vorlesungenberm0...,vorlesungenberm01kircgoog_tif/vorlesungenberm0...
4,1,vorlesungenberm00kircgoog_tif/vorlesungenberm0...,vorlesungenberm01kircgoog_tif/vorlesungenberm0...
5,1,vorlesungenberm00kircgoog_tif/vorlesungenberm0...,vorlesungenberm01kircgoog_tif/vorlesungenberm0...
...,...,...,...
461,30,vorlesungenberm00kircgoog_tif/vorlesungenberm0...,vorlesungenberm01kircgoog_tif/vorlesungenberm0...
462,30,vorlesungenberm00kircgoog_tif/vorlesungenberm0...,vorlesungenberm01kircgoog_tif/vorlesungenberm0...
463,30,vorlesungenberm00kircgoog_tif/vorlesungenberm0...,vorlesungenberm01kircgoog_tif/vorlesungenberm0...
464,30,vorlesungenberm00kircgoog_tif/vorlesungenberm0...,vorlesungenberm01kircgoog_tif/vorlesungenberm0...
465,30,vorlesungenberm00kircgoog_tif/vorlesungenberm0...,vorlesungenberm01kircgoog_tif/vorlesungenberm0...

In [7]:
# from IPython.display import HTML

# first_paths00 = df.groupby('lect').first()['path00']
# first_paths01 = df.groupby('lect').first()['path01']

# imgs00 = ''.join([f'<div><img src="{path}"></div>' for path in first_paths00])
# imgs01 = ''.join([f'<div><img src="{path}"></div>' for path in first_paths01])

# style5 = '"display: grid; grid-template-columns: repeat(5, 1fr);"'

# html00 = f'<div style={style5}>{imgs00}</div>'
# html01 = f'<div style={style5}>{imgs01}</div>'

In [8]:
# display(HTML(html00))

In [9]:
# display(HTML(html01))